### PR TITLE
Support unicode syntax

### PR DESCRIPTION
**Pull request by unclechu**
List of possible unicode operators may not be complete but could be extended later when needed.

### CODE REVIEW

**Comment by raichoo** [comment]
I'm not really fond of adding unicode syntax to the plugin since it complicates the regexes quite a bit. It also does not end with highlighting, after highlighting works one needs to fix indentation to support it and indentation is already a hairy business. So I'm really reluctant to even consider this. Maybe as an optional feature but that would not prevent adding more conditional branches in the indentation in the future once this is introduced. So currently I'd say "No" on this one, even though you have put some effort into the patch.

**Comment by unclechu** [comment]
@raichoo So, you're about to close it and leave me to care about my own fork or you'd expect me to improve it and make this feature be optional?

**Comment by raichoo** [comment]
I'll probably leave this issue open for a while since others might want to chime in and maybe have some suggestions. I have a somewhat radical stance on unicode syntax in source code but maybe there are good reasons to support it which I haven't heard yet. For now I'd certainly would recommend that you maintain a fork. I hope this doesn't put you off regarding future contributions.

**Comment by unclechu** [comment]
@raichoo I have an idea, since I'm anyway maintaining [my own repo](https://github.com/unclechu/haskell-vim) for unicode support, how about adding another repo (e.g. `neovimhaskell/haskell-with-unicode-vim`) which I will maintain by myself, merging updates from original repo from time to time, so you wouldn't care about it?

**Comment by unclechu** [comment]
Just a bump after about a year.

**Comment by unclechu** [comment]
@raichoo My proposal about separated repo is still valid.

**Comment by Achierius** [comment]
Shoot, wish I'd seen this PR before I ended up doing it myself; I actually didn't run into _all_ that much difficulty with the regexes, as most all of the Unicode extensions don't touch too heavily on 'structural' parts of the language. Definitely a +1 to having this integrated if possible, though.

**Comment by unclechu** [comment]
@raichoo I seem to be not the only one who wants this feature. Here you can see @Achierius also struggled adding support for unicode being not aware this pull request exists, @DeCentN2Madness left a thumbs up reaction, and @mkohlhaas created similar merge request #134. Maybe worth considering to merge this?

**Comment by unclechu** [comment]
I myself still use my own fork for years now.

**Comment by unclechu** [comment]
I decided to maintain my own fork with Unicode syntax support that would be just a separate plugin from this one.

The fork: https://github.com/wenzel-hoffman/haskell-with-unicode.vim

@Achierius and @DeCentN2Madness, you can find this fork useful.

I’m closing this merge request, since 2018 it wasn’t merged and and it seems it will never be. I also created a pull request with a change in README to point people who are looking for `UnicodeSyntax` support to that fork to not bother you with requests to add this feature and to not spend their time implementing it themselves. See #135

**Pull request closed without merging**
