### PR TITLE
Added support for proportional character

### LINKED ISSUE #41: Support GHC Unicode extension highlighting
Right now, the character ∷ does not cause the same highlighting as ::, even though they are treated the same by [GHC with the Unicode extension](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/syntax-extns.html#unicode-syntax).

### PR DESCRIPTION
**Pull request by siddharthist**
Fixes #41

### CODE REVIEW

**Comment by raichoo** [comment]
Hi,
thanks for the patch. There are three things that I'd like to see done before I merge this (nitpicky me! :) )

* This will complicate regexes therefore I'd like this feature to be optional. Add a flag to turn this on.
* There are more occurences of `::` in the highlighter. I'd be great if you'd patch those as well.
* Documentation would be nice. Mention this in the feature list of `haskell-vim` and document the flag to turn it on.

It would be great if you'd add things like unicode arrows to the patch as well (maybe some time in the future).

Kind regards,
raichoo

**Comment by siddharthist** [comment]
Hey @raichoo, I don't really know how to add flags, so I can't make progress on this by myself. If you'd be willing to help, I think we could knock out basic unicode support pretty fast, though. Also I'm a total vimscript ametuer, I just patched this on my `haskell.vim` file and thought I'd share.

**Comment by raichoo** [comment]
You basically check for a global variable like so `if exists('g:haskell_enable_quantification') && g:haskell_enable_quantification == 1`. That's pretty much it. The rest should become clear if you look at the syntax file.

**Comment by raichoo** [comment]
If this still does not help you, feel free to ask me specific questions :)

**Comment by siddharthist** [comment]
For sure, I might give it a try when I have some more time.

**Comment by raichoo** [comment]
It's probably a matter of a few minutes of work. I could do this myself, but I'd like to have external contributors as well and this is a low hanging fruit ready for the taking :)

**Comment by myfreeweb** [comment]
Hey, looks like this got removed when some things changed… Currently, `∷` is not highlighted :(

**Comment by raichoo** [comment]
It has never been merged. I didn't want to complicate the parser more (which it currently is) and wanted this to be optional. That change sadly was never made and the MR is not incompatible with the code base. Patches welcome.

**Pull request closed without merging**
